manja_sourcing_homepage:
    pattern:  /manja
    defaults: { _controller: ManjaSourcingBundle:Manja:index }

manja_sourcing_prices:
    pattern:  /sourcing/prices
    defaults: { _controller: ManjaSourcingBundle:Manja:listPrices }

manja_sourcing_list:
    pattern:  /sourcing/list/{data}
    defaults: { _controller: ManjaSourcingBundle:Manja:list }
    requirements: 
        data: accessorie_length|accessorie_piece|chain|contact|diamond|finding|metal|pearl|stone|stone_variety|supplier

manja_sourcing_add:
    pattern:  /sourcing/add/{data}
    defaults: { _controller: ManjaSourcingBundle:Manja:add }
    requirements: 
        data: accessorie_length|accessorie_piece|chain|contact|diamond|finding|metal|pearl|stone|supplier

manja_sourcing_remove:
    pattern:  /sourcing/remove/{category}/{id}
    defaults: { _controller: ManjaSourcingBundle:Manja:remove }
    requirements: 
        data: accessorie_length|accessorie_piece|chain|contact|diamond|finding|metal|pearl|stone|supplier

manja_sourcing_item_sheet:
    pattern: /sourcing/itemsheet/{category}/{id}
    defaults: { _controller: ManjaSourcingBundle:Manja:itemSheet }
    requirements:
        category: accessorie_length|accessorie_piece|chain|contact|diamond|finding|metal|pearl|stone|supplier
