parameters:
#    manja_user.example.class: Manja\UserBundle\Example

services:
#    manja_user.example:
#        class: %manja_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
