parameters:
#    manja_stock.example.class: Manja\Bundle\StockBundle\Example

services:
#    manja_stock.example:
#        class: %manja_stock.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
